# SPDX-License-Identifier: GPL-2.0-only
# usbdisplay is loaded by usb-displayd.service after the real fb0 driver owns fb0.
# Keep this package-owned placeholder so upgrades replace older early-load files.
